module.exports = [
    {
        id: "dHIqPGXAw8Q",
        image: "/image/ecoleta.jpg",
        title: "Projeto Ecoleta",
        duration: "HTML, CSS",
        price: "JavaScript",
        featured: true,
    },
    {
        id: "z3UhG7TbAMM",
        image: "/image/Alicia.jpg",
        title: "Projeto Psicologa Alícia Curado",
        duration: "HTML, CSS",
        price: "JavaScript",
        featured: true,
    },
    {
        id: "dhqz53LaA0o",
        image: "/image/barbearia.jpg",
        title: "Projeto para Barbearia",
        duration: "HTML, CSS",
        price: "JavaScript",
    },
    {
        id: "FD0lct8jD_s",
        image: "/image/Site_de_afiliado.jpg",
        title: "Projeto para Afiliados",
        duration: "HTML, CSS",
        price: "JavaScript",
    },
    {
        id: "9RNHKKYJvg8",
        image: "https://usefors.com.br/wp-content/uploads/2020/07/dark.jpg",
        title: "Projeto bla bla bla bla",
        duration: "10:54",
        price: "Free",
        featured: true,
    },
    {
        id: "vF2vxj8HZIk",
        image: "https://usefors.com.br/wp-content/uploads/2020/07/dark.jpg",
        title: "Projeto bla bla bla bla",
        duration: "10:54",
        price: "Free",
    },   
]